### ISSUE TITLE
Install vuetify

### ISSUE THREAD

**Issue by alvar0hurtad0** [Herugor/facturacionautonomos-front#1]
Necesitamos instalar vuetify para poder utilizar los componentes.

La historia estará completa cuando podamos utilizar componentes de vuetify sin que se produzcan errores.

**Comment by alvar0hurtad0** [comment]
https://vuetifyjs.com/en/getting-started/quick-start

**Comment by Herugor** [comment]
El código parece estar bien, dado que funciona y se muestra correctamente en codepen.io, pero no consigo que se muestren los estilos ni los componentes de vuetify en local.
He reinstalado vuetify de nuevo sin éxito. La versión es la correcta, e incluso se ha declarado en el index.html de forma temporal, pero sigue sin mostrar bien los estilos.
Presupongo que tiene que ser mi máquina, pero se me escapa dónde puede estar el fallo.

**Comment by alvar0hurtad0** [comment]
Ya está Sr.

Básicamente estaba el codigo duplicado en index.html y en la app javascript.

Lo he dejado commiteado y subido
