### ISSUE TITLE
Crear un toolbar vacio

### ISSUE THREAD

**Issue by alvar0hurtad0** [Herugor/facturacionautonomos-front#3]
Vamos a hacer nuestro primer componente.

Para ello vamos a hacer un fichero toolbar.vue dentro de src/components.

Utilizará el componente de vuetify v-toolbar.

https://vuetifyjs.com/en/components/toolbars

La issue estará hecha cuando:

- [ ]  tengamos el componente insertado en nuestra aplicacion  (App.vue)
- [ ] podamos leer` Facturacion Autonomos` a la izquierda.
- [ ] Podamos leer `Hola userName` a la derecha.

**Comment by Herugor** [comment]
Me da que tengo mal instalado el proyecto. Quizá elegí mal el webpack. No consigo ver el toolbar y juraría que el código está bien.
